name: Packaging(Linux)

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  PRODUCT: notion
  # win or mac, depending on which sources you would like to build from.
  PRODUCT_PLATFORM: win
  NOTION_BINARY: notion.exe
  WIN_VERSION: 2.0.9
  NOTION_DMG: notion.dmg
  MAC_VERSION: 2.0.8
  ELECTRON_VERSION: 8.5.3
  RELEASE: 1
  ARCH: x86_64

jobs:
  appimage-pack:
    name: appimage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source code
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          ref: main
      - name: Checkout Source code
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y --no-install-recommends install \
            nodejs \
            p7zip-full \
            imagemagick \
            fakeroot \
            wget \
            curl
      - name: Install Nodejs Tools
        run: |
          sudo npm -g install asar electron-packager electron-builder
      - name: Get Notion Installer
        run: |
          wget https://desktop-release.notion-static.com/Notion%20Setup%20${WIN_VERSION}.exe -O ${NOTION_BINARY}
      - name: Packaging appimage
        run: |
          mkdir -p build
          7z x $GITHUB_WORKSPACE/${NOTION_BINARY} -obuild/notion
          7z x "$GITHUB_WORKSPACE/build/notion/\$PLUGINSDIR/app-64.7z" -obuild/bundle
          asar extract $GITHUB_WORKSPACE/build/bundle/resources/app.asar build/app

          sed -i 's/"Notion"/"notion-desktop"/' $GITHUB_WORKSPACE/build/app/package.json
          preamble='"version": "'
          sed -i -r "s/$preamble(.+?)\"/$preamble\1-${PRODUCT_PLATFORM}\"/" $GITHUB_WORKSPACE/build/app/package.json

          rm -rf $GITHUB_WORKSPACE/build/app/node_modules

          export npm_config_target=${ELECTRON_VERSION}
          export npm_config_arch=x64
          export npm_config_target_arch=x64
          export npm_config_disturl=https://electronjs.org/headers
          export npm_config_runtime=electron
          export npm_config_build_from_source=true

          HOME=~/.electron-gyp sudo npm install --prefix build/app

          convert 'build/app/icon.ico[0]' build/app/icon.png

          electron-packager build/app notion \
            --platform linux \
            --arch x64 \
            --out build/dist \
            --electron-version ${ELECTRON_VERSION} \
            --executable-name notion-desktop

          chmod +x $GITHUB_WORKSPACE/build/dist/notion-linux-x64/notion-desktop
          asar pack $GITHUB_WORKSPACE/build/dist/notion-linux-x64/resources/app $GITHUB_WORKSPACE/build/dist/notion-linux-x64/resources/app.asar
          rm -rf $GITHUB_WORKSPACE/build/dist/notion-linux-x64/resources/app
          cd $GITHUB_WORKSPACE/build/dist
          tar -Jcvf notion-linux-x64.tar.xz notion-linux-x64


      # electron-builder --linux appImage \
      #   --projectDir build/dist/notion-linux-x64 \
      #   --prepackaged /build/out \
      #   --x64 \
      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: ${{ github.workspace }}/build/dist/notion-linux-x64.tar.xz
